plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id "me.modmuss50.mod-publish-plugin" version "2.0.0"
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}
publishMods {
    file = remapJar.archiveFile
    changelog = rootProject.file("CHANGELOG.md").text
    type = STABLE
    version = "${project.property('version')}"
    modLoaders.add("fabric")
    modLoaders.add("quilt")

    curseforge {
        displayName = file.map { it.asFile.name }
        projectId = property("curseforge_id")
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        changelogType = "markdown"

        minecraftVersions.addAll(property("publish_minecraft_versions").split(",") as List<String>)

        client = true
        server = false
        requires("fabric-api")
    }

    modrinth {
        displayName = "Better FireFlies ${project.property('version')}"
        projectId = property("modrinth_id")
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")

        minecraftVersions.addAll(property("publish_minecraft_versions").split(",") as List<String>)

        requires("fabric-api")
    }
}